### ISSUE TITLE
use llama

### ISSUE THREAD

**Issue by zjjJacinthe** [ExplainableML/Vision_by_Language#3]
I want to replace the gpt-turbo-3.5 model in the code with a llama series model. What do I need to do?

**Comment by sgk98** [comment]
Hey,
The gpt-3.5-turbo model call is being made here: https://github.com/ExplainableML/Vision_by_Language/blob/master/src/utils.py#L180. You would need to replace the API call with your call to a LLaMa model, the prompt (with the in-context examples) is already available here.
