### ISSUE TITLE
Regarding datasets

### ISSUE THREAD

**Issue by neouyghur** [ExplainableML/Vision_by_Language#6]
Hi,
I tried to reproduce your results. However, I found some broken links when I downloaded the FASHION-IQ dataset.  Have you faced such a problem? If so, how you solved it? Thanks.

**Comment by sgk98** [comment]
Hey, I was rechecking the Fashion-IQ download instructions (https://github.com/postBG/CosMo.pytorch), and I think you can directly download the images using this drive link (https://drive.google.com/drive/folders/14JG_w0V58iex62bVUHSBDYGBUECbDdx9?usp=sharing). This should avoid the problem of directly trying to download the images from URLs. Let me know if this works for you.

**Comment by neouyghur** [comment]
Hi @sgk98, that folder does not include images.

**Comment by neouyghur** [comment]
FYI, I found this repo which might include all the images. https://huggingface.co/datasets/Plachta/FashionIQ/tree/main

**Comment by sgk98** [comment]
You could also use the yandex link here: https://github.com/XiaoxiaoGuo/fashion-iq/issues/18

**Comment by neouyghur** [comment]
Thanks.
